---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bookstack
  annotations:
    nfs.io/storage-path: "data01/bookstack/config"
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bookstack-mariadb
  annotations:
    nfs.io/storage-path: "data01/bookstack/db"
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
