apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: bookstack
spec:
  provider: vault
  secretObjects:
  - secretName: bookstack
    type: Opaque
    data: 
    - objectName: MYSQL_USER
      key: MYSQL_USER
    - objectName: MYSQL_PASSWORD
      key: MYSQL_PASSWORD
    - objectName: MYSQL_DATABASE
      key: MYSQL_DATABASE
    - objectName: MYSQL_ROOT_PASSWORD
      key: MYSQL_ROOT_PASSWORD
    - objectName: URL
      key: URL
  parameters:
    vaultAddress: 'http://vault.vault:8200'
    vaultKubernetesMountPath: 'k8s-vault-csi'
    roleName: bookstack
    objects: |
      - objectName: "MYSQL_USER"
        secretPath: "apps-kv/data/bookstack/database"
        secretKey: "MYSQL_USER"
      - objectName: "MYSQL_PASSWORD"
        secretPath: "apps-kv/data/bookstack/database"
        secretKey: "MYSQL_PASSWORD"
      - objectName: "MYSQL_DATABASE"
        secretPath: "apps-kv/data/bookstack/database"
        secretKey: "MYSQL_DATABASE"
      - objectName: "MYSQL_ROOT_PASSWORD"
        secretPath: "apps-kv/data/bookstack/database"
        secretKey: "MYSQL_ROOT_PASSWORD"
      - objectName: "URL"
        secretPath: "apps-kv/data/bookstack/config"
        secretKey: "URL"
