kind: Deployment
apiVersion: apps/v1
metadata:
  name: bookstack
  labels:
    app: bookstack
    part-of: bookstack
  annotations:
    keel.sh/policy: force
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@hourly"
    keel.sh/match-tag: true
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstack
      part-of: bookstack
  template:
    metadata:
      labels:
        app: bookstack
        part-of: bookstack
    spec:
      serviceAccountName: bookstack
      containers:
      - name: bookstack
        image: ghcr.io/linuxserver/bookstack:latest
        ports:
        - name: bookstack
          containerPort: 80
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: UMASK
          value: "022"
        - name: APP_URL
          valueFrom:
            secretKeyRef:
              name: bookstack
              key: URL
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: bookstack
              key: MYSQL_USER
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: bookstack
              key: MYSQL_DATABASE
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: bookstack
              key: MYSQL_PASSWORD
        - name: DB_HOST
          value: "mariadb"
        volumeMounts:
        - name: bookstack
          mountPath: /config
        readinessProbe:
          tcpSocket:
            port: bookstack
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: bookstack
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          limits:
            memory: 32Mi
          requests:
            memory: 16Mi
      volumes:
      - name: bookstack
        persistentVolumeClaim:
          claimName: bookstack
